name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      working-directory: ./client 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      - name: Install Dependencies
        run: npm install
      # Run npm run build
      - name: Build
        run: npm run build
      # Run npm start
      - name: Start
        run: npm start
      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
            build: npm run build
            start: npm run start:dev
            wait-on: 'http://localhost:3000'
            wait-on-timeout: 60
            browser: chrome             
