name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      # Run npm run build
      - name: Build
        run: npm run build
        working-directory: ./client
      # Run npm start
      - name: Start
        run: npm start
        working-directory: ./client
      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
